// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow/access.proto

package flow

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

type GetLatestBlockHeaderRequest struct {
	IsSealed             bool     `protobuf:"varint,1,opt,name=is_sealed,json=isSealed,proto3" json:"is_sealed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLatestBlockHeaderRequest) Reset()         { *m = GetLatestBlockHeaderRequest{} }
func (m *GetLatestBlockHeaderRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestBlockHeaderRequest) ProtoMessage()    {}
func (*GetLatestBlockHeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{2}
}

func (m *GetLatestBlockHeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestBlockHeaderRequest.Unmarshal(m, b)
}
func (m *GetLatestBlockHeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestBlockHeaderRequest.Marshal(b, m, deterministic)
}
func (m *GetLatestBlockHeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestBlockHeaderRequest.Merge(m, src)
}
func (m *GetLatestBlockHeaderRequest) XXX_Size() int {
	return xxx_messageInfo_GetLatestBlockHeaderRequest.Size(m)
}
func (m *GetLatestBlockHeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestBlockHeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestBlockHeaderRequest proto.InternalMessageInfo

func (m *GetLatestBlockHeaderRequest) GetIsSealed() bool {
	if m != nil {
		return m.IsSealed
	}
	return false
}

type GetBlockHeaderByIDRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHeaderByIDRequest) Reset()         { *m = GetBlockHeaderByIDRequest{} }
func (m *GetBlockHeaderByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockHeaderByIDRequest) ProtoMessage()    {}
func (*GetBlockHeaderByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{3}
}

func (m *GetBlockHeaderByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHeaderByIDRequest.Unmarshal(m, b)
}
func (m *GetBlockHeaderByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHeaderByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockHeaderByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHeaderByIDRequest.Merge(m, src)
}
func (m *GetBlockHeaderByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockHeaderByIDRequest.Size(m)
}
func (m *GetBlockHeaderByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHeaderByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHeaderByIDRequest proto.InternalMessageInfo

func (m *GetBlockHeaderByIDRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetBlockHeaderByHeightRequest struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHeaderByHeightRequest) Reset()         { *m = GetBlockHeaderByHeightRequest{} }
func (m *GetBlockHeaderByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockHeaderByHeightRequest) ProtoMessage()    {}
func (*GetBlockHeaderByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{4}
}

func (m *GetBlockHeaderByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHeaderByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockHeaderByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHeaderByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockHeaderByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHeaderByHeightRequest.Merge(m, src)
}
func (m *GetBlockHeaderByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockHeaderByHeightRequest.Size(m)
}
func (m *GetBlockHeaderByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHeaderByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHeaderByHeightRequest proto.InternalMessageInfo

func (m *GetBlockHeaderByHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type BlockHeaderResponse struct {
	Block                *BlockHeader `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BlockHeaderResponse) Reset()         { *m = BlockHeaderResponse{} }
func (m *BlockHeaderResponse) String() string { return proto.CompactTextString(m) }
func (*BlockHeaderResponse) ProtoMessage()    {}
func (*BlockHeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{5}
}

func (m *BlockHeaderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeaderResponse.Unmarshal(m, b)
}
func (m *BlockHeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeaderResponse.Marshal(b, m, deterministic)
}
func (m *BlockHeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeaderResponse.Merge(m, src)
}
func (m *BlockHeaderResponse) XXX_Size() int {
	return xxx_messageInfo_BlockHeaderResponse.Size(m)
}
func (m *BlockHeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeaderResponse proto.InternalMessageInfo

func (m *BlockHeaderResponse) GetBlock() *BlockHeader {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetLatestBlockRequest struct {
	IsSealed             bool     `protobuf:"varint,1,opt,name=is_sealed,json=isSealed,proto3" json:"is_sealed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLatestBlockRequest) Reset()         { *m = GetLatestBlockRequest{} }
func (m *GetLatestBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestBlockRequest) ProtoMessage()    {}
func (*GetLatestBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{6}
}

func (m *GetLatestBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestBlockRequest.Unmarshal(m, b)
}
func (m *GetLatestBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestBlockRequest.Marshal(b, m, deterministic)
}
func (m *GetLatestBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestBlockRequest.Merge(m, src)
}
func (m *GetLatestBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetLatestBlockRequest.Size(m)
}
func (m *GetLatestBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestBlockRequest proto.InternalMessageInfo

func (m *GetLatestBlockRequest) GetIsSealed() bool {
	if m != nil {
		return m.IsSealed
	}
	return false
}

type GetBlockByIDRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByIDRequest) Reset()         { *m = GetBlockByIDRequest{} }
func (m *GetBlockByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByIDRequest) ProtoMessage()    {}
func (*GetBlockByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{7}
}

func (m *GetBlockByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByIDRequest.Unmarshal(m, b)
}
func (m *GetBlockByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByIDRequest.Merge(m, src)
}
func (m *GetBlockByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByIDRequest.Size(m)
}
func (m *GetBlockByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByIDRequest proto.InternalMessageInfo

func (m *GetBlockByIDRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetBlockByHeightRequest struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByHeightRequest) Reset()         { *m = GetBlockByHeightRequest{} }
func (m *GetBlockByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHeightRequest) ProtoMessage()    {}
func (*GetBlockByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{8}
}

func (m *GetBlockByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHeightRequest.Merge(m, src)
}
func (m *GetBlockByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHeightRequest.Size(m)
}
func (m *GetBlockByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHeightRequest proto.InternalMessageInfo

func (m *GetBlockByHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type BlockResponse struct {
	Block                *Block   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{9}
}

func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (m *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(m, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetCollectionByIDRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCollectionByIDRequest) Reset()         { *m = GetCollectionByIDRequest{} }
func (m *GetCollectionByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetCollectionByIDRequest) ProtoMessage()    {}
func (*GetCollectionByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{10}
}

func (m *GetCollectionByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollectionByIDRequest.Unmarshal(m, b)
}
func (m *GetCollectionByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollectionByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetCollectionByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollectionByIDRequest.Merge(m, src)
}
func (m *GetCollectionByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetCollectionByIDRequest.Size(m)
}
func (m *GetCollectionByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollectionByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollectionByIDRequest proto.InternalMessageInfo

func (m *GetCollectionByIDRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type CollectionResponse struct {
	Collection           *Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CollectionResponse) Reset()         { *m = CollectionResponse{} }
func (m *CollectionResponse) String() string { return proto.CompactTextString(m) }
func (*CollectionResponse) ProtoMessage()    {}
func (*CollectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{11}
}

func (m *CollectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionResponse.Unmarshal(m, b)
}
func (m *CollectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionResponse.Marshal(b, m, deterministic)
}
func (m *CollectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionResponse.Merge(m, src)
}
func (m *CollectionResponse) XXX_Size() int {
	return xxx_messageInfo_CollectionResponse.Size(m)
}
func (m *CollectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionResponse proto.InternalMessageInfo

func (m *CollectionResponse) GetCollection() *Collection {
	if m != nil {
		return m.Collection
	}
	return nil
}

type SendTransactionRequest struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendTransactionRequest) Reset()         { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()    {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{12}
}

func (m *SendTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRequest.Unmarshal(m, b)
}
func (m *SendTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SendTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRequest.Merge(m, src)
}
func (m *SendTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRequest.Size(m)
}
func (m *SendTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRequest proto.InternalMessageInfo

func (m *SendTransactionRequest) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type SendTransactionResponse struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionResponse) Reset()         { *m = SendTransactionResponse{} }
func (m *SendTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*SendTransactionResponse) ProtoMessage()    {}
func (*SendTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{13}
}

func (m *SendTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionResponse.Unmarshal(m, b)
}
func (m *SendTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionResponse.Marshal(b, m, deterministic)
}
func (m *SendTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionResponse.Merge(m, src)
}
func (m *SendTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_SendTransactionResponse.Size(m)
}
func (m *SendTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionResponse proto.InternalMessageInfo

func (m *SendTransactionResponse) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetTransactionRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionRequest) Reset()         { *m = GetTransactionRequest{} }
func (m *GetTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionRequest) ProtoMessage()    {}
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{14}
}

func (m *GetTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionRequest.Unmarshal(m, b)
}
func (m *GetTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionRequest.Merge(m, src)
}
func (m *GetTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionRequest.Size(m)
}
func (m *GetTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionRequest proto.InternalMessageInfo

func (m *GetTransactionRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type TransactionResponse struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{15}
}

func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (m *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(m, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type TransactionResultResponse struct {
	Status               TransactionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=flow.TransactionStatus" json:"status,omitempty"`
	Events               []*Event          `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransactionResultResponse) Reset()         { *m = TransactionResultResponse{} }
func (m *TransactionResultResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResultResponse) ProtoMessage()    {}
func (*TransactionResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{16}
}

func (m *TransactionResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResultResponse.Unmarshal(m, b)
}
func (m *TransactionResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResultResponse.Marshal(b, m, deterministic)
}
func (m *TransactionResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResultResponse.Merge(m, src)
}
func (m *TransactionResultResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResultResponse.Size(m)
}
func (m *TransactionResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResultResponse proto.InternalMessageInfo

func (m *TransactionResultResponse) GetStatus() TransactionStatus {
	if m != nil {
		return m.Status
	}
	return TransactionStatus_STATUS_UNKNOWN
}

func (m *TransactionResultResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type GetAccountRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{17}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type GetAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{18}
}

func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type ExecuteScriptAtLatestBlockRequest struct {
	Script               []byte   `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteScriptAtLatestBlockRequest) Reset()         { *m = ExecuteScriptAtLatestBlockRequest{} }
func (m *ExecuteScriptAtLatestBlockRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteScriptAtLatestBlockRequest) ProtoMessage()    {}
func (*ExecuteScriptAtLatestBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{19}
}

func (m *ExecuteScriptAtLatestBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteScriptAtLatestBlockRequest.Unmarshal(m, b)
}
func (m *ExecuteScriptAtLatestBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteScriptAtLatestBlockRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteScriptAtLatestBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteScriptAtLatestBlockRequest.Merge(m, src)
}
func (m *ExecuteScriptAtLatestBlockRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteScriptAtLatestBlockRequest.Size(m)
}
func (m *ExecuteScriptAtLatestBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteScriptAtLatestBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteScriptAtLatestBlockRequest proto.InternalMessageInfo

func (m *ExecuteScriptAtLatestBlockRequest) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type ExecuteScriptAtBlockIDRequest struct {
	BlockId              []byte   `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Script               []byte   `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteScriptAtBlockIDRequest) Reset()         { *m = ExecuteScriptAtBlockIDRequest{} }
func (m *ExecuteScriptAtBlockIDRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteScriptAtBlockIDRequest) ProtoMessage()    {}
func (*ExecuteScriptAtBlockIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{20}
}

func (m *ExecuteScriptAtBlockIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteScriptAtBlockIDRequest.Unmarshal(m, b)
}
func (m *ExecuteScriptAtBlockIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteScriptAtBlockIDRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteScriptAtBlockIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteScriptAtBlockIDRequest.Merge(m, src)
}
func (m *ExecuteScriptAtBlockIDRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteScriptAtBlockIDRequest.Size(m)
}
func (m *ExecuteScriptAtBlockIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteScriptAtBlockIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteScriptAtBlockIDRequest proto.InternalMessageInfo

func (m *ExecuteScriptAtBlockIDRequest) GetBlockId() []byte {
	if m != nil {
		return m.BlockId
	}
	return nil
}

func (m *ExecuteScriptAtBlockIDRequest) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type ExecuteScriptAtBlockHeightRequest struct {
	BlockHeight          uint64   `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Script               []byte   `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteScriptAtBlockHeightRequest) Reset()         { *m = ExecuteScriptAtBlockHeightRequest{} }
func (m *ExecuteScriptAtBlockHeightRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteScriptAtBlockHeightRequest) ProtoMessage()    {}
func (*ExecuteScriptAtBlockHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{21}
}

func (m *ExecuteScriptAtBlockHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteScriptAtBlockHeightRequest.Unmarshal(m, b)
}
func (m *ExecuteScriptAtBlockHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteScriptAtBlockHeightRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteScriptAtBlockHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteScriptAtBlockHeightRequest.Merge(m, src)
}
func (m *ExecuteScriptAtBlockHeightRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteScriptAtBlockHeightRequest.Size(m)
}
func (m *ExecuteScriptAtBlockHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteScriptAtBlockHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteScriptAtBlockHeightRequest proto.InternalMessageInfo

func (m *ExecuteScriptAtBlockHeightRequest) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ExecuteScriptAtBlockHeightRequest) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type ExecuteScriptResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteScriptResponse) Reset()         { *m = ExecuteScriptResponse{} }
func (m *ExecuteScriptResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteScriptResponse) ProtoMessage()    {}
func (*ExecuteScriptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{22}
}

func (m *ExecuteScriptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteScriptResponse.Unmarshal(m, b)
}
func (m *ExecuteScriptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteScriptResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteScriptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteScriptResponse.Merge(m, src)
}
func (m *ExecuteScriptResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteScriptResponse.Size(m)
}
func (m *ExecuteScriptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteScriptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteScriptResponse proto.InternalMessageInfo

func (m *ExecuteScriptResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetEventsRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	StartBlock           uint64   `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock             uint64   `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{23}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

func (m *GetEventsRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetEventsRequest) GetStartBlock() uint64 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *GetEventsRequest) GetEndBlock() uint64 {
	if m != nil {
		return m.EndBlock
	}
	return 0
}

type GetEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b85aa3526a6984b3, []int{24}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

func (m *GetEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "flow.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "flow.PingResponse")
	proto.RegisterType((*GetLatestBlockHeaderRequest)(nil), "flow.GetLatestBlockHeaderRequest")
	proto.RegisterType((*GetBlockHeaderByIDRequest)(nil), "flow.GetBlockHeaderByIDRequest")
	proto.RegisterType((*GetBlockHeaderByHeightRequest)(nil), "flow.GetBlockHeaderByHeightRequest")
	proto.RegisterType((*BlockHeaderResponse)(nil), "flow.BlockHeaderResponse")
	proto.RegisterType((*GetLatestBlockRequest)(nil), "flow.GetLatestBlockRequest")
	proto.RegisterType((*GetBlockByIDRequest)(nil), "flow.GetBlockByIDRequest")
	proto.RegisterType((*GetBlockByHeightRequest)(nil), "flow.GetBlockByHeightRequest")
	proto.RegisterType((*BlockResponse)(nil), "flow.BlockResponse")
	proto.RegisterType((*GetCollectionByIDRequest)(nil), "flow.GetCollectionByIDRequest")
	proto.RegisterType((*CollectionResponse)(nil), "flow.CollectionResponse")
	proto.RegisterType((*SendTransactionRequest)(nil), "flow.SendTransactionRequest")
	proto.RegisterType((*SendTransactionResponse)(nil), "flow.SendTransactionResponse")
	proto.RegisterType((*GetTransactionRequest)(nil), "flow.GetTransactionRequest")
	proto.RegisterType((*TransactionResponse)(nil), "flow.TransactionResponse")
	proto.RegisterType((*TransactionResultResponse)(nil), "flow.TransactionResultResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "flow.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "flow.GetAccountResponse")
	proto.RegisterType((*ExecuteScriptAtLatestBlockRequest)(nil), "flow.ExecuteScriptAtLatestBlockRequest")
	proto.RegisterType((*ExecuteScriptAtBlockIDRequest)(nil), "flow.ExecuteScriptAtBlockIDRequest")
	proto.RegisterType((*ExecuteScriptAtBlockHeightRequest)(nil), "flow.ExecuteScriptAtBlockHeightRequest")
	proto.RegisterType((*ExecuteScriptResponse)(nil), "flow.ExecuteScriptResponse")
	proto.RegisterType((*GetEventsRequest)(nil), "flow.GetEventsRequest")
	proto.RegisterType((*GetEventsResponse)(nil), "flow.GetEventsResponse")
}

func init() { proto.RegisterFile("flow/access.proto", fileDescriptor_b85aa3526a6984b3) }

var fileDescriptor_b85aa3526a6984b3 = []byte{
	// 849 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x6d, 0x4f, 0xdb, 0x48,
	0x10, 0x16, 0x21, 0x84, 0x64, 0x12, 0x72, 0xb0, 0x81, 0xbc, 0x38, 0x97, 0x83, 0x18, 0x9d, 0xb8,
	0x17, 0x01, 0x77, 0xe1, 0xa4, 0x3b, 0x5d, 0x5b, 0xaa, 0xa4, 0x85, 0x40, 0x55, 0x2a, 0xe4, 0xf0,
	0xa1, 0xe2, 0x43, 0x91, 0x63, 0x6f, 0xc1, 0x6a, 0x64, 0x87, 0xec, 0x86, 0x96, 0xbf, 0xdc, 0x5f,
	0x51, 0x65, 0xbd, 0x6b, 0xef, 0xc6, 0x1b, 0x17, 0xf5, 0x5b, 0x76, 0xe6, 0x99, 0x67, 0x66, 0xbc,
	0xb3, 0xcf, 0x04, 0x36, 0x3e, 0x8e, 0x82, 0xcf, 0x87, 0xb6, 0xe3, 0x60, 0x42, 0x0e, 0xc6, 0x93,
	0x80, 0x06, 0x28, 0x3b, 0x33, 0x19, 0x15, 0xe6, 0xc0, 0x3e, 0xf5, 0xa8, 0x87, 0xb9, 0xcb, 0x5c,
	0x83, 0xe2, 0xa5, 0xe7, 0xdf, 0x5a, 0xf8, 0x7e, 0x8a, 0x09, 0x35, 0xcb, 0x50, 0x0a, 0x8f, 0x64,
	0x1c, 0xf8, 0x04, 0x9b, 0xff, 0x43, 0xb3, 0x8f, 0xe9, 0x5b, 0x9b, 0x62, 0x42, 0x7b, 0xa3, 0xc0,
	0xf9, 0x74, 0x86, 0x6d, 0x17, 0x4f, 0x38, 0x1c, 0x35, 0xa1, 0xe0, 0x91, 0x1b, 0x82, 0xed, 0x11,
	0x76, 0xeb, 0x4b, 0x3b, 0x4b, 0xbf, 0xe5, 0xad, 0xbc, 0x47, 0x06, 0xec, 0x6c, 0xfe, 0x09, 0x8d,
	0x3e, 0x96, 0xa3, 0x7a, 0x8f, 0xe7, 0xaf, 0x45, 0x64, 0x19, 0x32, 0x5e, 0x18, 0x52, 0xb2, 0x32,
	0x9e, 0x6b, 0xfe, 0x0b, 0xad, 0x79, 0xf0, 0x19, 0xf6, 0x6e, 0xef, 0xa8, 0x08, 0xa8, 0x42, 0xee,
	0x8e, 0x19, 0x58, 0x50, 0xd6, 0xe2, 0x27, 0xf3, 0x18, 0x2a, 0x4a, 0x61, 0x61, 0xe1, 0x68, 0x0f,
	0x56, 0x86, 0x33, 0x33, 0x43, 0x17, 0x3b, 0x1b, 0x07, 0xb3, 0xe6, 0x0f, 0x64, 0x64, 0xe8, 0x37,
	0xff, 0x81, 0x2d, 0xb5, 0xc3, 0x27, 0xf5, 0xf6, 0x2b, 0x54, 0x44, 0xb9, 0x69, 0x5d, 0xfd, 0x0d,
	0xb5, 0x18, 0xf6, 0xb4, 0x7e, 0x3a, 0xb0, 0xc6, 0xcb, 0xe0, 0x9d, 0xb4, 0xd5, 0x4e, 0x8a, 0x52,
	0x27, 0xa2, 0x87, 0x3f, 0xa0, 0xde, 0xc7, 0xf4, 0x55, 0x30, 0x1a, 0x61, 0x87, 0x7a, 0x81, 0x9f,
	0x56, 0xd2, 0x29, 0xa0, 0x18, 0x18, 0x25, 0xf9, 0x0b, 0xc0, 0x89, 0xac, 0x3c, 0xd3, 0x7a, 0x98,
	0x49, 0x42, 0x4b, 0x18, 0xf3, 0x02, 0xaa, 0x03, 0xec, 0xbb, 0x57, 0x13, 0xdb, 0x27, 0x36, 0x27,
	0x0b, 0x33, 0x1e, 0x41, 0x91, 0xc6, 0x56, 0xf5, 0x02, 0x64, 0xb8, 0x8c, 0x32, 0x7f, 0x87, 0x5a,
	0x82, 0x8e, 0xd7, 0x36, 0xdf, 0xc1, 0x1e, 0xbb, 0x31, 0x4d, 0xe2, 0x79, 0xe0, 0x1b, 0xa8, 0xe8,
	0xf8, 0x7e, 0xa8, 0xbe, 0x7b, 0x68, 0xa8, 0x5c, 0xd3, 0x11, 0x8d, 0x18, 0x0f, 0x21, 0x47, 0xa8,
	0x4d, 0xa7, 0x84, 0x91, 0x95, 0x3b, 0xb5, 0x04, 0xd9, 0x80, 0xb9, 0x2d, 0x0e, 0x43, 0xbb, 0x90,
	0xc3, 0x0f, 0xd8, 0xa7, 0xa4, 0x9e, 0xd9, 0x59, 0x8e, 0x2f, 0xf5, 0x64, 0x66, 0xb3, 0xb8, 0xcb,
	0xdc, 0x87, 0x8d, 0x3e, 0xa6, 0x5d, 0xc7, 0x09, 0xa6, 0x7e, 0x34, 0x36, 0x75, 0x58, 0xb5, 0x5d,
	0x77, 0x82, 0x09, 0xe1, 0x8d, 0x8a, 0xa3, 0xf9, 0x02, 0x90, 0x0c, 0x8f, 0xde, 0xc1, 0xaa, 0x1d,
	0x9a, 0x78, 0xa3, 0x6b, 0x61, 0x2a, 0x81, 0x13, 0x5e, 0xf3, 0x19, 0xb4, 0x4f, 0xbe, 0x60, 0x67,
	0x4a, 0xf1, 0xc0, 0x99, 0x78, 0x63, 0xda, 0xd5, 0xbd, 0x89, 0x2a, 0xe4, 0x08, 0xf3, 0xf2, 0xe4,
	0xfc, 0x64, 0x5a, 0xd0, 0x9a, 0x0b, 0x66, 0x61, 0xf1, 0x14, 0x36, 0x20, 0xcf, 0x46, 0xf5, 0x26,
	0xba, 0xa0, 0x55, 0x76, 0x3e, 0x77, 0x25, 0xce, 0x8c, 0xc2, 0xf9, 0x21, 0x51, 0x10, 0x7f, 0xbd,
	0xf2, 0x2b, 0x6a, 0x43, 0x29, 0xe4, 0x55, 0xde, 0x52, 0x71, 0x18, 0x23, 0x17, 0xf2, 0xef, 0xc3,
	0x96, 0xc2, 0x1f, 0x7d, 0xb2, 0x4d, 0x58, 0x79, 0xb0, 0x47, 0x53, 0xcc, 0x0b, 0x0d, 0x0f, 0xa6,
	0x0b, 0xeb, 0x7d, 0x4c, 0xd9, 0x0d, 0x11, 0x91, 0x1d, 0x41, 0x96, 0x3e, 0x8e, 0x43, 0x60, 0xc1,
	0x62, 0xbf, 0xd1, 0x36, 0x14, 0x09, 0xb5, 0x27, 0xf4, 0x26, 0x7c, 0xb4, 0x19, 0x56, 0x10, 0x30,
	0x13, 0xab, 0x7f, 0xa6, 0x2b, 0xd8, 0x77, 0xb9, 0x7b, 0x99, 0xb9, 0xf3, 0xd8, 0x77, 0x99, 0xd3,
	0xfc, 0x8f, 0xdd, 0xb9, 0xc8, 0xc2, 0x0b, 0x8a, 0xa7, 0x65, 0x69, 0xe1, 0xb4, 0x74, 0xbe, 0x16,
	0xa0, 0xd0, 0x65, 0xa2, 0xdf, 0xbd, 0x3c, 0x47, 0xfb, 0x90, 0x9d, 0xe9, 0x38, 0xe2, 0x63, 0x2d,
	0x49, 0xbc, 0x81, 0x64, 0x13, 0xcf, 0x70, 0x05, 0x9b, 0x3a, 0x99, 0x47, 0xed, 0x10, 0x9b, 0xb2,
	0x02, 0x8c, 0x46, 0x52, 0x59, 0x05, 0xeb, 0x25, 0x9b, 0xc8, 0xb9, 0x05, 0x80, 0xb6, 0x23, 0x4e,
	0xfd, 0x6a, 0x48, 0x63, 0x7c, 0x0f, 0x55, 0xfd, 0x96, 0x40, 0xbb, 0x7a, 0x56, 0x65, 0x5a, 0xd2,
	0x98, 0x7b, 0x50, 0x56, 0xbb, 0x44, 0x4d, 0x5d, 0xef, 0x82, 0xa9, 0x22, 0xab, 0xb0, 0xe0, 0x38,
	0x86, 0x92, 0xbc, 0x14, 0x50, 0x43, 0xad, 0x49, 0xee, 0x51, 0x1b, 0x7f, 0xca, 0x46, 0x4c, 0xd9,
	0x16, 0xa8, 0x35, 0xcf, 0xa1, 0x76, 0xa4, 0xe5, 0xb9, 0x60, 0x43, 0xa4, 0xae, 0x03, 0xf4, 0x4b,
	0x44, 0xa4, 0xdd, 0x13, 0x46, 0x3d, 0xa1, 0xf6, 0x82, 0xee, 0x1d, 0xfc, 0x34, 0x27, 0xcd, 0xe8,
	0xe7, 0x10, 0xac, 0x5f, 0x00, 0x46, 0x6b, 0x81, 0x97, 0xf3, 0x9d, 0xb1, 0x4f, 0x2d, 0xd3, 0xc5,
	0x9f, 0x5a, 0xc3, 0xd6, 0x48, 0x2a, 0xb3, 0x3a, 0xb6, 0x09, 0x5d, 0x4e, 0xe7, 0xdb, 0xd6, 0xf1,
	0xc9, 0x6a, 0xfe, 0x12, 0x20, 0x16, 0x52, 0x54, 0x8b, 0xb8, 0x54, 0x25, 0x16, 0x1f, 0x4c, 0xa3,
	0xb9, 0x43, 0x30, 0x16, 0x4b, 0x29, 0xda, 0xe3, 0xaf, 0xf7, 0x7b, 0x62, 0x6b, 0x34, 0x35, 0xc0,
	0x28, 0xc7, 0x35, 0x54, 0xf5, 0x8a, 0x2b, 0x5e, 0x42, 0xaa, 0x1e, 0xa7, 0x73, 0x27, 0xeb, 0x97,
	0x94, 0x77, 0x41, 0xfd, 0x49, 0x6d, 0x4e, 0xcf, 0xf1, 0x1c, 0x0a, 0x91, 0xd0, 0xa1, 0x6a, 0xf4,
	0x29, 0x15, 0x7d, 0x35, 0x6a, 0x09, 0x7b, 0x18, 0xdd, 0xcb, 0x5d, 0xb3, 0xbf, 0xb4, 0xc3, 0x1c,
	0xfb, 0x13, 0x7b, 0xf4, 0x2d, 0x00, 0x00, 0xff, 0xff, 0x24, 0x4e, 0xaa, 0xac, 0xf4, 0x0a, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccessAPIClient is the client API for AccessAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccessAPIClient interface {
	// Ping is used to check if the access node is alive and healthy.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// GetLatestBlockHeader gets the latest sealed or unsealed block header.
	GetLatestBlockHeader(ctx context.Context, in *GetLatestBlockHeaderRequest, opts ...grpc.CallOption) (*BlockHeaderResponse, error)
	// GetBlockHeaderByID gets a block header by ID.
	GetBlockHeaderByID(ctx context.Context, in *GetBlockHeaderByIDRequest, opts ...grpc.CallOption) (*BlockHeaderResponse, error)
	// GetBlockHeaderByHeight gets a block header by height.
	GetBlockHeaderByHeight(ctx context.Context, in *GetBlockHeaderByHeightRequest, opts ...grpc.CallOption) (*BlockHeaderResponse, error)
	// GetLatestBlock gets the full payload of the latest sealed or unsealed block.
	GetLatestBlock(ctx context.Context, in *GetLatestBlockRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	// GetBlockByID gets a full block by ID.
	GetBlockByID(ctx context.Context, in *GetBlockByIDRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	// GetBlockByHeight gets a full block by height.
	GetBlockByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	// GetCollectionByID gets a collection by ID.
	GetCollectionByID(ctx context.Context, in *GetCollectionByIDRequest, opts ...grpc.CallOption) (*CollectionResponse, error)
	// SendTransaction submits a transaction to the network.
	SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error)
	// GetTransaction gets a transaction by ID.
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	// GetTransactionResult gets the result of a transaction.
	GetTransactionResult(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*TransactionResultResponse, error)
	// GetAccount gets an account by address.
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	// ExecuteScriptAtLatestBlock executes a read-only Cadance script against the latest sealed execution state.
	ExecuteScriptAtLatestBlock(ctx context.Context, in *ExecuteScriptAtLatestBlockRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error)
	// ExecuteScriptAtBlockID executes a ready-only Cadence script against the execution state at the block with the given ID.
	ExecuteScriptAtBlockID(ctx context.Context, in *ExecuteScriptAtBlockIDRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error)
	// ExecuteScriptAtBlockHeight executes a ready-only Cadence script against the execution state at the given block height.
	ExecuteScriptAtBlockHeight(ctx context.Context, in *ExecuteScriptAtBlockHeightRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error)
	// GetEvents retrieves events matching the given query.
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
}

type accessAPIClient struct {
	cc *grpc.ClientConn
}

func NewAccessAPIClient(cc *grpc.ClientConn) AccessAPIClient {
	return &accessAPIClient{cc}
}

func (c *accessAPIClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) GetLatestBlockHeader(ctx context.Context, in *GetLatestBlockHeaderRequest, opts ...grpc.CallOption) (*BlockHeaderResponse, error) {
	out := new(BlockHeaderResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/GetLatestBlockHeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) GetBlockHeaderByID(ctx context.Context, in *GetBlockHeaderByIDRequest, opts ...grpc.CallOption) (*BlockHeaderResponse, error) {
	out := new(BlockHeaderResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/GetBlockHeaderByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) GetBlockHeaderByHeight(ctx context.Context, in *GetBlockHeaderByHeightRequest, opts ...grpc.CallOption) (*BlockHeaderResponse, error) {
	out := new(BlockHeaderResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/GetBlockHeaderByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) GetLatestBlock(ctx context.Context, in *GetLatestBlockRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/GetLatestBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) GetBlockByID(ctx context.Context, in *GetBlockByIDRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/GetBlockByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) GetBlockByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/GetBlockByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) GetCollectionByID(ctx context.Context, in *GetCollectionByIDRequest, opts ...grpc.CallOption) (*CollectionResponse, error) {
	out := new(CollectionResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/GetCollectionByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error) {
	out := new(SendTransactionResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/SendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) GetTransactionResult(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*TransactionResultResponse, error) {
	out := new(TransactionResultResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/GetTransactionResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) ExecuteScriptAtLatestBlock(ctx context.Context, in *ExecuteScriptAtLatestBlockRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error) {
	out := new(ExecuteScriptResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/ExecuteScriptAtLatestBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) ExecuteScriptAtBlockID(ctx context.Context, in *ExecuteScriptAtBlockIDRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error) {
	out := new(ExecuteScriptResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/ExecuteScriptAtBlockID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) ExecuteScriptAtBlockHeight(ctx context.Context, in *ExecuteScriptAtBlockHeightRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error) {
	out := new(ExecuteScriptResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/ExecuteScriptAtBlockHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessAPIClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, "/flow.AccessAPI/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessAPIServer is the server API for AccessAPI service.
type AccessAPIServer interface {
	// Ping is used to check if the access node is alive and healthy.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// GetLatestBlockHeader gets the latest sealed or unsealed block header.
	GetLatestBlockHeader(context.Context, *GetLatestBlockHeaderRequest) (*BlockHeaderResponse, error)
	// GetBlockHeaderByID gets a block header by ID.
	GetBlockHeaderByID(context.Context, *GetBlockHeaderByIDRequest) (*BlockHeaderResponse, error)
	// GetBlockHeaderByHeight gets a block header by height.
	GetBlockHeaderByHeight(context.Context, *GetBlockHeaderByHeightRequest) (*BlockHeaderResponse, error)
	// GetLatestBlock gets the full payload of the latest sealed or unsealed block.
	GetLatestBlock(context.Context, *GetLatestBlockRequest) (*BlockResponse, error)
	// GetBlockByID gets a full block by ID.
	GetBlockByID(context.Context, *GetBlockByIDRequest) (*BlockResponse, error)
	// GetBlockByHeight gets a full block by height.
	GetBlockByHeight(context.Context, *GetBlockByHeightRequest) (*BlockResponse, error)
	// GetCollectionByID gets a collection by ID.
	GetCollectionByID(context.Context, *GetCollectionByIDRequest) (*CollectionResponse, error)
	// SendTransaction submits a transaction to the network.
	SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionResponse, error)
	// GetTransaction gets a transaction by ID.
	GetTransaction(context.Context, *GetTransactionRequest) (*TransactionResponse, error)
	// GetTransactionResult gets the result of a transaction.
	GetTransactionResult(context.Context, *GetTransactionRequest) (*TransactionResultResponse, error)
	// GetAccount gets an account by address.
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	// ExecuteScriptAtLatestBlock executes a read-only Cadance script against the latest sealed execution state.
	ExecuteScriptAtLatestBlock(context.Context, *ExecuteScriptAtLatestBlockRequest) (*ExecuteScriptResponse, error)
	// ExecuteScriptAtBlockID executes a ready-only Cadence script against the execution state at the block with the given ID.
	ExecuteScriptAtBlockID(context.Context, *ExecuteScriptAtBlockIDRequest) (*ExecuteScriptResponse, error)
	// ExecuteScriptAtBlockHeight executes a ready-only Cadence script against the execution state at the given block height.
	ExecuteScriptAtBlockHeight(context.Context, *ExecuteScriptAtBlockHeightRequest) (*ExecuteScriptResponse, error)
	// GetEvents retrieves events matching the given query.
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
}

// UnimplementedAccessAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAccessAPIServer struct {
}

func (*UnimplementedAccessAPIServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedAccessAPIServer) GetLatestBlockHeader(ctx context.Context, req *GetLatestBlockHeaderRequest) (*BlockHeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestBlockHeader not implemented")
}
func (*UnimplementedAccessAPIServer) GetBlockHeaderByID(ctx context.Context, req *GetBlockHeaderByIDRequest) (*BlockHeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockHeaderByID not implemented")
}
func (*UnimplementedAccessAPIServer) GetBlockHeaderByHeight(ctx context.Context, req *GetBlockHeaderByHeightRequest) (*BlockHeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockHeaderByHeight not implemented")
}
func (*UnimplementedAccessAPIServer) GetLatestBlock(ctx context.Context, req *GetLatestBlockRequest) (*BlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestBlock not implemented")
}
func (*UnimplementedAccessAPIServer) GetBlockByID(ctx context.Context, req *GetBlockByIDRequest) (*BlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByID not implemented")
}
func (*UnimplementedAccessAPIServer) GetBlockByHeight(ctx context.Context, req *GetBlockByHeightRequest) (*BlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByHeight not implemented")
}
func (*UnimplementedAccessAPIServer) GetCollectionByID(ctx context.Context, req *GetCollectionByIDRequest) (*CollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionByID not implemented")
}
func (*UnimplementedAccessAPIServer) SendTransaction(ctx context.Context, req *SendTransactionRequest) (*SendTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (*UnimplementedAccessAPIServer) GetTransaction(ctx context.Context, req *GetTransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (*UnimplementedAccessAPIServer) GetTransactionResult(ctx context.Context, req *GetTransactionRequest) (*TransactionResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionResult not implemented")
}
func (*UnimplementedAccessAPIServer) GetAccount(ctx context.Context, req *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (*UnimplementedAccessAPIServer) ExecuteScriptAtLatestBlock(ctx context.Context, req *ExecuteScriptAtLatestBlockRequest) (*ExecuteScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteScriptAtLatestBlock not implemented")
}
func (*UnimplementedAccessAPIServer) ExecuteScriptAtBlockID(ctx context.Context, req *ExecuteScriptAtBlockIDRequest) (*ExecuteScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteScriptAtBlockID not implemented")
}
func (*UnimplementedAccessAPIServer) ExecuteScriptAtBlockHeight(ctx context.Context, req *ExecuteScriptAtBlockHeightRequest) (*ExecuteScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteScriptAtBlockHeight not implemented")
}
func (*UnimplementedAccessAPIServer) GetEvents(ctx context.Context, req *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}

func RegisterAccessAPIServer(s *grpc.Server, srv AccessAPIServer) {
	s.RegisterService(&_AccessAPI_serviceDesc, srv)
}

func _AccessAPI_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_GetLatestBlockHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestBlockHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).GetLatestBlockHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/GetLatestBlockHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).GetLatestBlockHeader(ctx, req.(*GetLatestBlockHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_GetBlockHeaderByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockHeaderByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).GetBlockHeaderByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/GetBlockHeaderByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).GetBlockHeaderByID(ctx, req.(*GetBlockHeaderByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_GetBlockHeaderByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockHeaderByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).GetBlockHeaderByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/GetBlockHeaderByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).GetBlockHeaderByHeight(ctx, req.(*GetBlockHeaderByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_GetLatestBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).GetLatestBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/GetLatestBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).GetLatestBlock(ctx, req.(*GetLatestBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_GetBlockByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).GetBlockByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/GetBlockByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).GetBlockByID(ctx, req.(*GetBlockByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_GetBlockByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).GetBlockByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/GetBlockByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).GetBlockByHeight(ctx, req.(*GetBlockByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_GetCollectionByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).GetCollectionByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/GetCollectionByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).GetCollectionByID(ctx, req.(*GetCollectionByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).SendTransaction(ctx, req.(*SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_GetTransactionResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).GetTransactionResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/GetTransactionResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).GetTransactionResult(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_ExecuteScriptAtLatestBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteScriptAtLatestBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).ExecuteScriptAtLatestBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/ExecuteScriptAtLatestBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).ExecuteScriptAtLatestBlock(ctx, req.(*ExecuteScriptAtLatestBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_ExecuteScriptAtBlockID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteScriptAtBlockIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).ExecuteScriptAtBlockID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/ExecuteScriptAtBlockID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).ExecuteScriptAtBlockID(ctx, req.(*ExecuteScriptAtBlockIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_ExecuteScriptAtBlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteScriptAtBlockHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).ExecuteScriptAtBlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/ExecuteScriptAtBlockHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).ExecuteScriptAtBlockHeight(ctx, req.(*ExecuteScriptAtBlockHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessAPI_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessAPIServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.AccessAPI/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessAPIServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccessAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flow.AccessAPI",
	HandlerType: (*AccessAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AccessAPI_Ping_Handler,
		},
		{
			MethodName: "GetLatestBlockHeader",
			Handler:    _AccessAPI_GetLatestBlockHeader_Handler,
		},
		{
			MethodName: "GetBlockHeaderByID",
			Handler:    _AccessAPI_GetBlockHeaderByID_Handler,
		},
		{
			MethodName: "GetBlockHeaderByHeight",
			Handler:    _AccessAPI_GetBlockHeaderByHeight_Handler,
		},
		{
			MethodName: "GetLatestBlock",
			Handler:    _AccessAPI_GetLatestBlock_Handler,
		},
		{
			MethodName: "GetBlockByID",
			Handler:    _AccessAPI_GetBlockByID_Handler,
		},
		{
			MethodName: "GetBlockByHeight",
			Handler:    _AccessAPI_GetBlockByHeight_Handler,
		},
		{
			MethodName: "GetCollectionByID",
			Handler:    _AccessAPI_GetCollectionByID_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _AccessAPI_SendTransaction_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _AccessAPI_GetTransaction_Handler,
		},
		{
			MethodName: "GetTransactionResult",
			Handler:    _AccessAPI_GetTransactionResult_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _AccessAPI_GetAccount_Handler,
		},
		{
			MethodName: "ExecuteScriptAtLatestBlock",
			Handler:    _AccessAPI_ExecuteScriptAtLatestBlock_Handler,
		},
		{
			MethodName: "ExecuteScriptAtBlockID",
			Handler:    _AccessAPI_ExecuteScriptAtBlockID_Handler,
		},
		{
			MethodName: "ExecuteScriptAtBlockHeight",
			Handler:    _AccessAPI_ExecuteScriptAtBlockHeight_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _AccessAPI_GetEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flow/access.proto",
}
